### ISSUE TITLE
Bug in point counting

### ISSUE THREAD

**Issue by mfpierre** [ionmx/world-cup-pool#5]
There is currently a bug in checking wether a prediction has been made or not.
In users there is an array of prediction but it's all set to true event if the user did not enter any score.

In my database I had a problem in point counting because some users just entered one of the team result expecting the other one to be 0 (and a 0 is display in front) but in the ruby cron there are no points awarded if one of the prediction is nil.
Also the points are displayed in front even if both score are nil (considered 0) and there is an even match result.

I've fixed the problem by setting the prediction to 0 if it's nil but it's not really great because event the users that did not play anything have points with even matchs.

I think the best solution should be to fix the prediction array setting it to true only if the user enter a team result and if it's true consider the other score to 0 if it's nil.

What do you think ?

**Comment by ionmx** [comment]
Each prediction is loaded with this line: 

https://github.com/ionmx/world-cup-pool/blob/master/js/app.js#L272

Is not using the relationship, so, I guess that the fix needs to be made in getScore() function...
